package teamSite.Commons

import io.gatling.core.Predef.{Simulation, _}
import io.gatling.http.Predef._


class BaseClass extends Simulation {

  protected val leaderboard = csv("leaderboards.csv").eager.random
  protected val sport = csv("sports.csv").eager.random
  protected val league = csv("leagues.csv").eager.random

  protected val httpProtocol = http
    .baseUrl("https://basketball-stage.synergysportstech.com/api") // Here is the root for all relative URLs
    .contentTypeHeader("application/json")
    .userAgentHeader(
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:16.0) Gecko/20100101 Firefox/16.0"
    )
    .authorizationHeader("Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1RjUxREM1RTc3MkM1RUNGNjc5NEY2RThEQzI1RDY2MzBGMEVCQ0FSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6IkZmVWR4ZWR5eGV6MmVVOXVqY0pkWmpEdzY4byJ9.eyJuYmYiOjE2NTgzOTAwNjEsImV4cCI6MTY1ODM5MzY2MSwiaXNzIjoiaHR0cHM6Ly9hdXRoLXN0YWdlLnN5bmVyZ3lzcG9ydHN0ZWNoLmNvbSIsImF1ZCI6WyJhcGkuYmFza2V0YmFsbCIsImFwaS5zcG9ydCIsImFwaS5zZWN1cml0eSIsImFwaS5lZGl0b3IiLCJhcGkuY29uZmlnIiwiaHR0cHM6Ly9hdXRoLXN0YWdlLnN5bmVyZ3lzcG9ydHN0ZWNoLmNvbS9yZXNvdXJjZXMiXSwiY2xpZW50X2lkIjoiY2xpZW50LmJhc2tldGJhbGwudGVhbXNpdGUiLCJzdWIiOiI2MjJhMzY5ZDRmM2UyMTNjMmI5ZTc5ZmUiLCJhdXRoX3RpbWUiOjE2NTcwMTE0MDgsImlkcCI6ImxvY2FsIiwiZW1haWwiOiJkLnNyaXZhc3RhdkBzcG9ydHJhZGFyLmNvbSIsIm5hbWUiOiJTcml2YXN0YXYgRGhhcm1lbmRlciIsInNpZCI6IjNCNjI3N0RFOUU3NUMyMDA5NEE0RkNBODA1RTVBQTc0IiwiaWF0IjoxNjU3MDI0MjcwLCJzY29wZSI6WyJvcGVuaWQiLCJhcGkuY29uZmlnIiwiYXBpLnNlY3VyaXR5IiwiYXBpLmJhc2tldGJhbGwiLCJhcGkuc3BvcnQiLCJhcGkuZWRpdG9yIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.lSrUh2lwPtEcLXykdDoTOjRKuGh8z7mfDo298TFho5jnxZVMihlXTt9nWZv7Y-ZhSrTW_NKKdlt9SRfESwtJYm7qeprou7KY9bijpX8E5Cv_ujCu8g3BzzGbvu15tDL6dc9mBg_HJy655WafpiI7xbnX1iC7hq2CvpgHzSbBAB1ZtteQXeUh01EcKfQCSm9MAzrbduTvygxnq4VF2zjtAISl57ZT78Ral_gRdJ2nC9-k2TaEzVvysenX5UeRzMA8mSEa0m2nk-aPdibM8rB1Hp-K4_dZUa7w_2TNuFau_2qepMUnXMcOcwgN1E7HrQ6QxJuzS5Mdg4sfex1QbbRtFQ")
}